### ISSUE TITLE
onClick function not working

### ISSUE THREAD

**Issue by shivamahuja99** [letsdoit07/flutter_animated_fab_menu#1]
Stacked buttons onClick function not working

**Comment by GuillermoDLCO** [comment]
I have same problem, could you solved it?

**Comment by GuillermoDLCO** [comment]
#3

**Comment by GuillermoDLCO** [comment]
#3  After different tests, I came up with this simpler solution

**Comment by retroportalstudio** [comment]
Thanks for the fix mate! Kudos!
